ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/sensor/cci
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/common
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_flash.o
