ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/common
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/sensor/io
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_ois.o
