ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/common
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/sensor/io
obj-$(CONFIG_MSM_CSID) += msm_ispif.o
