ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/common
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/sensor
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/sensor/cci
obj-$(CONFIG_MSMB_CAMERA)   += msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o
