ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/common
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/sensor/io
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
