ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/isp/
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/sensor/io
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/common
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
