ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/common
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/msm_vb2
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/camera
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/sensor/io
ccflags-y += -Idrivers/misc/lenovo/camera/camera-driver/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
